version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=asdf
      - DB_USER=physionet
      - DB_NAME=physionet
      - DB_PASSWORD=password
      - DB_HOST=db
    command: bash -c "./wait-for-it.sh db:5432 && python /code/physionet-django/manage.py migrate && python /code/physionet-django/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code:ro
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=physionet
      - POSTGRES_USER=physionet
      - POSTGRES_PASSWORD=password