version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=physionet.settings.settings
      - ENVIRONMENT=development
      - SECRET_KEY=asdf
      - ALLOWED_HOSTS=localhost
      - DB_USER=physionet
      - DB_NAME=physionet
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - SITE_ID=4
      - EMAIL_HOST=localhost
      - DEFAULT_FROM_EMAIL=localhost@localhost
      - CONTACT_EMAIL=PhysioNet Contact <contact@dev.physionet.org>
      - SERVER_EMAIL='PhysioNet System <root@dev.physionet.org>'
      - ADMINS_NAME=PhysioNet Technical
      - ADMINS_MAIL=technical@dev.physionet.org
      - OCRID_REDIRECT_URI=http://127.0.0.1:8000/authorcid
      - DATACITE_API_URL=https://api.test.datacite.org/dois
      - DATACITE_PREFIX=
      - MEDIA_ROOT=/code/media
      - STATIC_ROOT=/data/pn-static
    stdin_open: true
    tty: true
    command: bash -c "./wait-for-it.sh db:5432 && poetry run /code/physionet-django/manage.py migrate && poetry run /code/physionet-django/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code:rw
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=physionet
      - POSTGRES_USER=physionet
      - POSTGRES_PASSWORD=password
    volumes:
    - db_data:/var/lib/postgres/data:rw
volumes:
  db_data:
