# Generated by Django 2.2.24 on 2022-02-21 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0052_auto_20220105_1219"),
        ("environment", "0002_billingsetup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDatasetGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$",
                                message="Invalid dataset group format.",
                            )
                        ],
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gcp_dataset_group",
                        to="project.PublishedProject",
                    ),
                ),
            ],
        ),
    ]
