# Generated by Django 2.2.27 on 2022-03-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0056_auto_20220223_0749"),
        ("environment", "0004_auto_20220309_0330"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_resource_name",
                    models.CharField(max_length=256, unique=True),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "In Progress"), (1, "Succeeded"), (2, "Failed")]
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Creating"),
                            (1, "Destroying"),
                            (2, "Starting"),
                            (3, "Pausing"),
                            (4, "Changing"),
                        ]
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="project.PublishedProject",
                    ),
                ),
            ],
        ),
    ]
