# Builds the PhysioNet docker image and runs tests on the `dev` branch and PRs against the `dev` branch.
# Publishes the image to DockerHub with `latest` tag when the action runs on the `dev` branch.
# Can be triggered manually to build, test and optionally publish any branch with a custom tag.
# All published images are also tagged with corresponding git commit sha.
#
# To run the tests locally in a similar environment to GitHub Actions you can use:
# $ docker-compose -f docker/docker-compose.test.yml build
# $ docker-compose -f docker/docker-compose.test.yml run --rm test
# $ docker-compose -f docker/docker-compose.test.yml down

name: Docker / Build, Test and Publish

on:
  push:
    branches:
      - dev
      - dockerhub_ci_gke
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      publish_tag:
        description: 'publish_tag: if supplied it will also publish the image as physionet/physionet:<publish_tag>'
        required: false

env:
  PROJECT_ID: healthdatanexus-dev
  GKE_CLUSTER: gke-test-1    # Add your cluster name here.
  GKE_ZONE: us-central1   # Add your cluster zone here.
  DEPLOYMENT_NAME: backend # Add your deployment name here.

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout physionet-build repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build physionet image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: physionet:latest
          load: true

      - name: Run tests
        run: docker-compose -f docker/docker-compose.test.yml run --rm test

      - name: Stop and remove containers
        run: docker-compose -f docker/docker-compose.test.yml down

      - name: Save physionet image
        if: github.ref == 'refs/heads/dev' ||  github.ref == 'refs/heads/dockerhub_ci_gke' || github.event.inputs.publish_tag
        run: docker save physionet:latest | gzip > /tmp/physionet.tar.gz

      - name: Upload physionet image
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dockerhub_ci_gke' || github.event.inputs.publish_tag
        uses: actions/upload-artifact@v2
        with:
          name: physionet
          path: /tmp/physionet.tar.gz

  publish:
    name: Publish to DockerHub
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dockerhub_ci_gke' || github.event.inputs.publish_tag
    environment: dockerhub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download physionet image
        uses: actions/download-artifact@v2
        with:
          name: physionet
          path: /tmp

      - name: Load physionet image
        run: gunzip -c /tmp/physionet.tar.gz | docker load

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push
        run: |
          docker tag physionet:latest physionet/physionet:${GITHUB_SHA}
          docker tag physionet:latest physionet/physionet:${{ github.event.inputs.publish_tag || 'latest' }}
          docker push physionet/physionet:${GITHUB_SHA}
          docker push physionet/physionet:${{ github.event.inputs.publish_tag || 'latest' }}

  deploy_ecs:
    name: Deploy GKE
    needs: publish
    environment: dockerhub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dockerhub_ci_gke'
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/backend-deployment backend=physionet/physionet:${GITHUB_SHA}