# a github action on the dev branch that performs a build - test in a docker container
name: physionet-build-test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout physionet-build repo
        uses: actions/checkout@v2

      - name: Build physionet docker image
        run: docker-compose -f docker/docker-compose.test.yml build

      - name: Run tests
        run: docker-compose -f docker/docker-compose.test.yml run --rm test

      - name: Stop and remove containers
        run: docker-compose -f docker/docker-compose.test.yml down
